<?php 
	$param = $param;
	$links = [];
?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional //EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><!--[if IE]><html xmlns="http://www.w3.org/1999/xhtml" class="ie"><![endif]--><!--[if !IE]><!--><html style="margin: 0;padding: 0;" xmlns="http://www.w3.org/1999/xhtml"><!--<![endif]--><head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Information - <?= ucfirst(strtolower($param['committee'])) ?> - Nächste Sitzung</title>
    <!--[if !mso]><!--><meta http-equiv="X-UA-Compatible" content="IE=edge" /><!--<![endif]-->
    <meta name="viewport" content="width=device-width" />
<style type="text/css">
	body {
 		margin: 0;
		padding: 10px;
		height: 90%;
		width: 90%;
		background-color: #ffffff;
	}
	html {
		margin: 0;
		padding: 0;
		height: 100%;
		width: 100%;
	}
	table {
		border-collapse: collapse;
		table-layout: fixed;
	}
	* {
		line-height: inherit;
	}
</style>
    <meta name="robots" content="noindex,nofollow" />
	<meta property="og:title" content="Sitzungsinfo - <?=  ucfirst(strtolower($param['committee'])) ?>" />
</head>
<body class="half-padding" style="margin: 0;padding: 10px;-webkit-text-size-adjust: 100%;, height: 90%; width: 90%;">
	<img style="display: block;height: auto;width: 100%;border: 0;max-width: 242px;" src="cid:logoattach" alt="Logo" width="242" />
	<h2>Informationen zur Nächsten Sitzung - <?=  ucfirst(strtolower($param['committee'])) ?></h2>
	<hr>
	<p><strong style="font-weight:bold; width: 200px; padding-left: 20px;">Sitzungsdatum:</strong> <?= $param['date']->format('d.m.Y'); ?>
	<br><strong style="font-weight:bold; width: 200px; padding-left: 20px;">Uhrzeit:</strong> <?= $param['date']->format('H:i'); ?>Uhr
	<br><strong style="font-weight:bold; width: 200px; padding-left: 20px;">Sitzungsleitung:</strong> <?= ($param['leitung'])? $param['leitung'] : '--- nicht vergeben ---'; ?>
	<br><strong style="font-weight:bold; width: 200px; padding-left: 20px;">Protokollierung:</strong> <?= ($param['leitung'])? $param['protokoll'] : '--- nicht vergeben ---'; ?></p>
	
	<p>Weitere Informationen können im vergangenen Protokoll, im <a href="https://wiki.stura.tu-ilmenau.de/leitfaden/sitzungsleitung">Sitzungs-Leitfaden [<?php echo count($links); $links[] = 'https://wiki.stura.tu-ilmenau.de/leitfaden/sitzungsleitung'; ?>]</a>, oder im <a href="<?= $param['toolLink'] ?>">Protokolltool [<?php echo count($links); $links[] = $param['toolLink'] ?>]</a> gefunden werden.
	<br>Solltet die oben genannten Personen zum Zeitpunkt der Sitzung verhindert sein, meldet euch bitte rechtzeitig ab <strong style="font-weight:bold;">und</strong> sucht eine Person, welche die Aufgabe übernimmt.</p>
	<hr>
	<h3>Links</h3>
	<p>
	<?php 
		$c = strlen(''.count($links));
		foreach ($links as $pos => $link){
			echo '['.str_pad($pos, $c, "0", STR_PAD_LEFT).'] - <a href="'.$link.'">'.$link.'</a><br>';
		}
	?>
	</p>
	<p style="font-size: 8px; font-size: 0.7rem; font-weight: bold; color: #555555;">Diese Nachricht wurde automatisch vom <?= BASE_TITLE ?> generiert.</p>
</body>
</html>