<?php 
	$param = $param;
	$links = [];
?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional //EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><!--[if IE]><html xmlns="http://www.w3.org/1999/xhtml" class="ie"><![endif]--><!--[if !IE]><!--><html style="margin: 0;padding: 0;" xmlns="http://www.w3.org/1999/xhtml"><!--<![endif]--><head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Protokollerinnerung - <?= ucfirst(strtolower($param['gremium'])) ?></title>
    <!--[if !mso]><!--><meta http-equiv="X-UA-Compatible" content="IE=edge" /><!--<![endif]-->
    <meta name="viewport" content="width=device-width" />
<style type="text/css">
	body {
 		margin: 0;
		padding: 10px;
		height: 90%;
		width: 90%;
		background-color: #ffffff;
	}
	html {
		margin: 0;
		padding: 0;
		height: 100%;
		width: 100%;
	}
	table {
		border-collapse: collapse;
		table-layout: fixed;
	}
	* {
		line-height: inherit;
	}
</style>
    <meta name="robots" content="noindex,nofollow" />
	<meta property="og:title" content="Protokollerinnerung - <?=  ucfirst(strtolower($param['gremium'])) ?>" />
</head>
<body class="half-padding" style="margin: 0;padding: 10px;-webkit-text-size-adjust: 100%;, height: 90%; width: 90%;">
	<img style="display: block;height: auto;width: 100%;border: 0;max-width: 242px;" src="cid:logoattach" alt="Logo" width="242" />
	<h2>Protokollerinnerung - <?=  ucfirst(strtolower($param['gremium'])) . ' - ' . $param['date'] ?></h2>
	<hr>
	<p>Das Protokoll der Sitzung vom <strong style="font-weight:bold; "><?= $param['date'] ?></strong> wurde noch nicht<?= $param['group'] == 'not_handled'? ' als Entwurf':'' ?> veröffentlicht<?= $param['group'] == 'agreed_but_draft'? 'aber bereits abgestimmt':'' ?>.</p>
	<?php if($param['member']) { ?> 
	<p>Protokoll-Verantwortlicher: <strong style="font-weight:bold; "><?php $param['member']['name']; ?></strong></p>
	<?php } ?>
	
	<p>Unter diesem <a href="<?= $param['protoLink'] ?>">Link [<?php echo count($links); $links[] = $param['protoLink'] ?>]</a> kann das schnell und einfach erledigt werden.</p>
	<hr>
	<h3>Links</h3>
	<p>
	<?php 
		$c = strlen(''.count($links));
		foreach ($links as $pos => $link){
			echo '['.str_pad($pos, $c, "0", STR_PAD_LEFT).'] - <a href="'.$link.'">'.$link.'</a><br>';
		}
	?>
	</p>
	<p style="font-size: 8px; font-size: 0.7rem; font-weight: bold; color: #555555;">Diese Nachricht wurde automatisch vom <?= BASE_TITLE ?> generiert.</p>
</body>
</html>