<h2>Sitzungseinladung</h2>

<h3>Geplante Sitzung</h3>
<div class="btn btn-success">Sitzung planen</div>
<div class="btn btn-danger">Sitzung absagen</div>
<h4>Stura - Mitglieder</h4>
<h3>Eingereichte Tops</h3>
<div class="btn btn-success">Neues Top erstellen</div>
<div class="silmph_top_counter_reset"></div>
<div class="card silmph_top">
	<div class="card-header headline" data-resort="" data-headline="Überschrift"><span class="top_counter">Top</span>Überschrift</div>
	<div class="topinfo">
		<span class="added"><i class="fa fa-fw fa-calendar"></i>2013-02-13</span>
		<span class="duration"><i class="fa fa-fw fa-clock-o"></i>5 min.</span>
		<span class="person"><i class="fa fa-fw fa-user"></i>Person</span>
		<span class="goal"><i class="fa fa-fw fa-location-arrow"></i>Zielsetzung</span>
	</div>
	<div class="card-body">
		<div class="text">text
anderer text
  - aufzählung
  - aufzählung 2
  
  * liste
  * liste2</div>
	  	<div class="text_rendered"></div>
	</div>
	<div class="buttons"><div class="edit btn btn-outline-secondary" title="Bearbeiten"></div><div class="remove btn btn-outline-danger" title="Löschen"></div></div>
	
</div>
<div class="card silmph_top">
	<div class="card-body">
	jhwekhk
	</div>
	</div>

<?php
