<?php $param = $param; echo $this->getChallenge() ?>
<h2>Sitzungseinladung</h2>

<h3>Geplante Sitzung</h3>
<div class="btn btn-success">Sitzung planen</div>
<div class="btn btn-danger">Sitzung absagen</div>
<h4>Stura - Mitglieder</h4>
<div class="mb-3 silmph_memberbox<?= (checkUserPermission('admin'))?' editmember':''; ?>">
	<button class="btn btn-secondary showtoggle" type="button">Anzeigen</button>
	<ul class="list-group mt-1 mb-1">
<?php 
	foreach ($param['member'] as $member){
		echo '<li class="member p-2 list-group-item"><span class="membername" data-id="'.$member['id'].'" data-name="'.$member['name'].'" data-management="'.$member['management'].'" data-protocol="'.$member['protocol'].'"></span><span class="delete btn btn-outline-danger"></span></li>';
	}
?>
	</ul>
<?php 
if(checkUserPermission('admin')){
	echo '<div class="form-row">';
	echo '<div class="form-group col-md-8 mb-0">';
	echo '<input class="newmember_name form-control" type="text" value="" placeholder="Neues Mitglied"></div>';
	echo '<div class="form-group col-md-4 mb-0">';
	echo '<button class="newmemberbtn btn btn-success w-100" type="button">Hinzufügen</button></div>';
	echo '</div>';
} ?>
</div>
<h3>Eingereichte Tops</h3>
<div class="btn btn-success">Neues Top erstellen</div>
<div class="silmph_top_counter_reset"></div>
<div class="silmph_toplist">
<?php


foreach($param['tops'] as $top){
	if (isset($top['used_on'])) continue;
	echo '<div class="card border-secondary silmph_top'.(($top['skip_next'])?' skipnext':'').(($top['guest'])?' guest':'').(isset($top['resort'])?' resort':'').'" data-tid="'.$top['id'].'" data-hash="'.$top['hash'].'">';
	echo "\t".'<div class="card-header headline" data-resort="'.($top['resort']?$top['resort']:'').'" data-level="'.$top['level'].'" data-headline="'.json_encode($top['headline']).'">'.
					((!$top['resort'])?
						'<span class="top_counter"></span>'
						:'<span class="top_resort">'.$param['resorts'][$top['resort']]['type'].' '.$param['resorts'][$top['resort']]['name'].'</span>')
					.'<span>'.$top['headline'].'</span>'
		."</div>\n";
	echo "\t<div class=\"topinfo text-secondary\">\n";
		echo '<span class="added">'.date_create($top['added_on'])->format('d.m.Y').'</span>'."\n";
		$minutes = 0;
		if (isset($top['expected_duration'])){
			$tmp = explode(':', $top['expected_duration']);
			$minutes = $tmp[0] * 60 + $tmp[1];
		}
		echo '<span class="duration">'.$minutes.' min.</span>'."\n";
		echo '<span class="person">'.((isset($top['person'])&&trim($top['person']))?$top['person']:'---').'</span>'."\n";
		echo '<span class="goal">'.(isset($top['goal'])?$top['goal']:'').'</span>'."\n";
		echo '<span class="guest">Gast</span>'."\n";
		echo '<span class="skipn">Aussetzten</span>'."\n";
	echo "\t</div>\n";
	echo "\t<div class=\"card-body\">\n";
		echo "\t\t<div class=\"text\">".$top['text']."</div>\n";
		echo '<input class="d-none" id="texttoggle_top_cb_'.$top['id'].'" type="checkbox" >';
		echo "\t\t<div class=\"text_rendered\"></div>\n";
		echo '<label class="texttoggle btn btn-outline-secondary" for="texttoggle_top_cb_'.$top['id'].'"></label>';
	echo "\t</div>\n";
	echo "\t".'<div class="buttons"><div class="edit btn btn-outline-secondary" title="Bearbeiten"></div><div class="remove btn btn-outline-danger" title="Löschen"></div><div class="skipn btn btn-outline-secondary" title="Aussetzten"></div></div>'."\n";
	echo "</div>\n";
}

?>
</div>
