<?php $param = $param; echo $this->getChallenge(); ?>
<img src="<?= BASE_SUBDIRECTORY ?>images/stura_head.svg" class="printonly stura-head">
<h2 class="headline printonly">Geplante Sitzung</h2>
<h2 class="headline noprint">Sitzungseinladung</h2>

<div class="card mb-3">
	<div class="card-body">
		<h3>Geplante Sitzung</h3>
        <div class="silmph_themenhead silmph_when printonly">
            <span>Wann?</span>
        </div>
		<div class="silmph_nprotolist mb-1 border border-secondary" data-meetinghour="<?= $param['settings']['meeting_hour'];?>" data-legislatur="<?= $param['legislatur']['number']; ?>" data-nthproto="<?= $param['nth-proto']; ?>">
			<div class="bg-warning npheadline">
	  			<div class="row p-2">
	    			<div class="col-3">Datum</div>
	    			<div class="col-3">Status</div>
					<div class="col-6">Optionen</div>
				</div>
			</div>
			<div class="npbody">
				<?php
					// state:
					// 0 - geplant 		- generated_url==null && invite_mail_done == 0
					// 1 - eingeladen	- generated_url==null && invite_mail_done == 1
					// 2 - erstellt 	- generated_url!=null
					$statelist = ['Geplant', 'Eingeladen', 'Erstellt'];
					foreach($param['newproto'] as $nproto){
						$state = ($nproto['generated_url'] != null)? 2 : (($nproto['invite_mail_done'])? 1 : 0);
						$disable_restore = false;
						if ($state == 2){
							$today = date_create();
							$npdate = date_create($nproto['date']);
							$npdate->setTime(0, 0);
							$diff1 = $today->getTimestamp() - $npdate->getTimestamp();
							if ( $diff1 > 3600 * 24 * $param['settings']['disable_restore'] ){
								$disable_restore = true;
							}
						} ?>
						<div class="nprotoelm row p-2" data-id="<?= $nproto['id'] ?>" data-hash="<?= (!$disable_restore)?$nproto['hash']:'' ?>" data-m="<?= $nproto['management']?$nproto['management']:'' ?>" data-p="<?= $nproto['protocol']?$nproto['protocol']:'' ?>">
							<div class="col-3"><?= date_create($nproto['date'])->format('d.m.Y H:i') ?></div>
	    					<div class="col-3"><?= $statelist[$state] ?></div>
							<div class="col-6">
								<?php if($state < 2){ ?>
									<button class="infoedit btn btn-outline-secondary" title="Info | Bearbeiten" type="button"><i class="fa fa-fw fa-info"></i></button>
                                    <button class="memberpdf btn btn-outline-secondary" title="Anwesenheitsliste" type="button"><i class="fa fa-fw fa-file-text-o"></i></button>
                                    <button class="send<?= ($nproto['invite_mail_done'])? ' resend':'' ?> btn btn-outline-secondary" title="Einladung<?= ($nproto['invite_mail_done'])? ' erneut':'' ?> versenden" type="button"><i class="fa fa-fw fa-envelope"></i></button>
									<button class="createp btn btn-outline-secondary" title="Protokoll erstellen" type="button">
										<span class="fa-stack2 fa-fw">
											<i class="fa fa-wikipedia-w fa-stack-1x"></i>
											<i class="fa fa-pencil fa-stack-1x text-success"></i>
										</span></button>
									<button class="cancel btn btn-outline-secondary" title="Planung entfernen" type="button"><i class="fa fa-fw fa-times"></i></button>
								<?php } else { ?>
									<a target="_blank" class="link btn btn-outline-secondary" href="<?= ($nproto['generated_url']? WIKI_URL.'/'.str_replace(':', '/', $param['protomap'][0]).'/'.$nproto['generated_url']: '#')?>" title="Zum Protokoll" type="button"><i class="fa fa-fw fa-link"></i></a>
                                    <button class="memberpdf btn btn-outline-secondary" title="Anwesenheitsliste" type="button"><i class="fa fa-fw fa-file-text-o"></i></button>
                                    <?php if ( !$disable_restore ){ ?>
                                        <button class="restore_one btn btn-outline-secondary" title="Ausgewählte Tops Wiederherstellen" type="button"><i class="fa fa-fw fa-recycle"></i></button>
										<button class="restore btn btn-outline-secondary" title="Alle Tops Wiederherstellen" type="button"><i class="fa fa-fw fa-stack-overflow"></i></button>
									<?php } ?>
								<?php } ?>
									
							</div>
						</div>
				<?php } ?>
			</div>
		</div>
		<div class="silmph_create_np btn btn-success mb-2">Neue Sitzung planen</div>
		<h4>Stura - Mitglieder</h4>
		<div class="silmph_memberbox<?= (checkUserPermission('admin'))?' editmember':' viewmember'; ?>">
			<button class="btn btn-secondary col-md-4  showtoggle" type="button" data-texttoggle="Verstecken">Anzeigen</button>
			<ul class="list-group mt-1 mb-1">
			<?php
				$memberOut = [
					'Gewählt' => [],
					'Angestellt' => [],
					'AG/Referat' => [],
					'Aktiv' => [],
				];
				foreach ($param['member'] as $m){
					if ($m['flag_elected']){
						$memberOut['Gewählt'][] = $m;
					} elseif($m['flag_stuff']) {
						$memberOut['Angestellt'][] = $m;
					} elseif($m['flag_ref']) {
						$memberOut['AG/Referat'][] = $m;
					} elseif($m['flag_active']) {
						$memberOut['Aktiv'][] = $m;
					}
				}
				foreach ($memberOut as $group => $members){
					if (count($members) > 0){
						echo '<li class="membergroup p-2 list-group-item bg-dark text-white font-weight-bold">'.$group.'</li>';
						foreach ($members as $m){
							echo '<li class="member p-2 list-group-item'.((!empty($m['overwrite']) && false!== strpos($m['overwrite'],'(ruhend)'))?' sleeping':'').'"><span class="membername" data-group="'.$group.'" data-id="'.$m['id'].'" data-job="'.(($m['job'])?'('.$m['job'].')':'').'" data-name="'.$m['name'].'" data-management="'.$m['management'].'" data-protocol="'.$m['protocol'].'"></span><span title="Ruhend (Toggle)" class="pendingtoggle btn btn-outline-danger"></span></li>';
						}
					}
				}
			?>
				</ul>
		</div>
	</div>
</div>

<h3>Eingereichte Tops</h3>
<div class="btn btn-success silmph_tcreate_btn">Top/Bericht erstellen</div>
<div class="silmph_top_counter_reset"></div>
<div class="silmph_themenhead printonly">
    <span>Wo?</span>
</div>
<div class="silmph_where printonly">
    <span>EAZ1337</span>
</div>
<div class="silmph_themenhead printonly">Themen</div>
<div class="silmph_toplist">
<?php

foreach($param['tops'] as $top){
	if (isset($top['used_on'])) continue;
	echo '<div id="top_'.substr($top['hash'], 0, 10).'" data-resort="'.($top['resort']?$top['resort']:'').'" data-intern="'.($top['intern']?1:'').'" class="card border-secondary silmph_top'.(($top['skip_next'])?' skipnext':'').(($top['guest'])?' guest':'').(($top['intern'])?' internal':'').(isset($top['resort'])?' resort':'').'" data-tid="'.$top['id'].'" data-hash="'.$top['hash'].'">';
	echo "\t".'<div class="card-header headline" data-resort="'.($top['resort']?$top['resort']:'').'" data-level="'.$top['level']."\" data-headline='".json_encode([$top['headline']])."'>".
					((!$top['resort'])?
						'<span class="top_counter"></span>'
						:'<span class="top_resort">'.$param['resorts'][$top['resort']]['type'].' '.$param['resorts'][$top['resort']]['name'].'</span>')
					.'<span>'.$top['headline'].'</span>'
		."</div>\n";
	echo "\t<div class=\"topinfo text-secondary\">\n";
		echo '<span class="added">'.date_create($top['added_on'])->format('d.m.Y H:i').'</span>'."\n";
		$minutes = 0;
		if (isset($top['expected_duration'])){
			$minutes = $top['expected_duration'];
		}
		echo '<span class="duration">'.$minutes.' min.</span>'."\n";
		echo '<span class="person">'.((isset($top['person'])&&trim($top['person']))?$top['person']:'---').'</span>'."\n";
		echo '<span class="goal">'.(isset($top['goal'])?$top['goal']:'').'</span>'."\n";
		echo '<span class="filecount"><a href="'.(BASE_SUBDIRECTORY.'files/npuploader?committee='.$param['committee'].'&tid='.$top['id'].'&gui=1&hash='.$top['hash']).'">'.$top['filecounter'].'</a></span>'."\n";
		echo '<span class="guest">Gast</span>'."\n";
		echo '<span class="skipn">Auf nächste Woche verschoben</span>'."\n";
	echo "\t</div>\n";
	echo "\t<div class=\"card-body\">\n";
		echo "\t\t<div class=\"text\">".$top['text']."</div>\n";
		echo '<input class="d-none" id="texttoggle_top_cb_'.$top['id'].'" type="checkbox" >';
		echo "\t\t<div class=\"text_rendered\"></div>\n";
		echo '<label class="texttoggle btn btn-outline-secondary" for="texttoggle_top_cb_'.$top['id'].'"></label>';
	echo "\t</div>\n";
	echo "\t".'<div class="buttons"><div class="edit btn btn-outline-secondary" title="Bearbeiten"></div><div class="remove btn btn-outline-danger" title="Löschen"></div><div class="skipn btn btn-outline-secondary" title="Auf nächste Woche verschieben"></div></div>'."\n";
	echo "</div>\n";
}

?>
    <div data-resort="" data-intern="" class="silmph_top printonly">
        <div class="card-header headline ui-sortable-handle"><span class="placeholder"></span><span>Berichte aus den Referaten und Fachschaftsräten</span></div>
    </div>
    <div data-resort="" data-intern="" class="silmph_top printonly">
        <div class="card-header headline ui-sortable-handle"><span class="placeholder"></span><span>Termine und Sonstiges</span></div>
    </div>
</div>
<div class="silmph_invitetext printonly">
    Der StuRa läd alle interessierten Studierenden ein, an den Treffen teilzunehmen. Die Sitzungen finden in der Regel hochschulöffentlich jeden Mittwoch um 19:00 Uhr im EAZ 1337/1338 statt.
</div>
