<?php $param = $param; echo $this->getChallenge(); ?>
<h2 class="headline printonly">Geplante Sitzung</h2>
<h2 class="headline noprint">Stura</h2>

<div class="card mb-3">
	<div class="card-body">
        <div class="invite-info">
            Der StuRa lädt alle interessierten Studierenden ein, an den Treffen teilzunehmen. Die Sitzungen finden in der Regel hochschulöffentlich jeden Mittwoch um <?= $param['settings']['meeting_hour'];?>:00 Uhr im <?= $param['settings']['meeting_room'];?> statt.
        </div>
		<h3>Nächste <?= (is_array($param['newproto']) && count($param['newproto']) > 1)?'geplanten Sitzungen':'geplante Sitzung' ?></h3>
		<div class="silmph_nprotolist mb-1 border border-secondary" data-meetinghour="<?= $param['settings']['meeting_hour'];?>" data-legislatur="<?= $param['legislatur']['number']; ?>" data-nthproto="<?= $param['nth-proto']; ?>">
			<div class="bg-warning npheadline">
	  			<div class="row p-2">
	    			<div class="col-3">Datum</div>
				</div>
			</div>
			<div class="npbody">
				<?php
					$printed_newprotos = 0;
					$now = date_create();
					foreach($param['newproto'] as $nproto){
						$npdate = date_create($nproto['date']);
						$printed_newprotos++;
						?>
						<div class="nprotoelm row p-2 m-0 border-top border-secondary">
							<div class="col-12"><?= date_create($nproto['date'])->format('d.m.Y H:i'). (($now->getTimestamp() > ($npdate->getTimestamp() + 18000))? ' (vergangen)':'') ?><?= ($nproto['room']?'<div style="color:#ee1212;font-weight:bold;">Die Sitzung wurde in einen anderen Raum verlegt und findet nun im "'.htmlspecialchars($nproto['room']).'" statt.</div>':'') ?></div>
						</div>
				<?php }
					if (!is_array($param['newproto']) || count($param['newproto']) == 0 || $printed_newprotos == 0){
						?>
						<div class="nprotoelm row p-2 m-0 border-top border-secondary">
							<div class="col-12"><div style="font-weight:bold;">Bisher ist keine Sitzung geplant. Bitte schaue später nocheinmal hier vorbei.</div></div>
						</div>
						<?php
					}
				?>
			</div>
		</div>
	</div>
</div>

<h3>Geplante Themen</h3>
<div class="silmph_top_counter_reset"></div>
<div class="silmph_toplist">
<?php

foreach($param['tops'] as $top){
	if (isset($top['used_on'])) continue;
	if (isset($top['intern'])&&$top['intern']) continue;
	if (isset($top['skip_next'])&&$top['skip_next']) continue;
	if (isset($top['resort'])&&$top['resort']) continue;
	?>
    <div data-resort="" data-intern="" class="silmph_top">
        <div class="card-header headline ui-sortable-handle"><span class="top_counter"></span><span><?= $top['headline']; ?></span>
        <?php
            echo "\t<div class=\"topinfo text-secondary\">\n";
            $minutes = 0;
            if (isset($top['expected_duration'])){
                $minutes = $top['expected_duration'];
            }
            echo '<span class="duration">'.$minutes.' min.</span>'."\n";
            echo '<span class="goal">'.(isset($top['goal'])?$top['goal']:'').'</span>'."\n";
            echo "\t</div>\n";
        ?>
        </div>
    </div>
    <?php
}
?>
    <div data-resort="" data-intern="" class="silmph_top">
        <div class="card-header headline ui-sortable-handle"><span class="placeholder"></span><span>Berichte aus den Referaten und Fachschaftsräten</span></div>
    </div>
    <div data-resort="" data-intern="" class="silmph_top">
        <div class="card-header headline ui-sortable-handle"><span class="placeholder"></span><span>Termine und Sonstiges</span></div>
    </div>
</div>
