<h3>Crawler</h3>
<p class="alert alert-warning"><strong>Diese Funktionen sind mit Vorsicht zu genießen. Es empfiehlt sich, vorher eine Sicherung der Datenbank anzulegen.</strong></p>


<div class="crawllinklist">
<p>
	<i>Crawlt Legislaturnummern anhand der Beschlussliste. Alte Werden nicht gelöscht. Da aber die Beschlüsse nicht weit genug in die Vergangenheit reichen, um alle Protokolle abzudecken, müssen mindestens die Legislatur 18 und 19 von Hand nachgetragen werden, wenn die Datenbank geleert wurde.</i><br>
	<a class="btn btn-outline-danger w-75" href="/crawl/legislatur">1. Crawl Legislatur</a>
</p>
<p>
	<i>Crawlt Beschlüsse anhand der Beschlussliste. Liest Protokolle anhand der Protokolliste im Wiki, matcht beide Listen und trägt beides in die Datenbank ein. Protokolle werden im Wiki weder verarbeitet, noch erstellt.<br>Führe diesen Befehl nur auf eine leere Datenbank aus.</i><br>
	<a class="btn btn-outline-danger w-75" href="/crawl/resoproto">2. Crawl Beschlüsse und Protokolle</a>
</p>
</div>
<?php
