<?= (isset($_SESSION['SILMPH']) && isset($_SESSION['SILMPH']['FORM_CHALLENGE_NAME']))? '<input type="hidden" id="fchal" name="'.$_SESSION['SILMPH']['FORM_CHALLENGE_NAME'].'" value="'.$_SESSION['SILMPH']['FORM_CHALLENGE_VALUE'].'">': ''?>

<div class="half_container mail_settings admin"><h3 class="noprint">E-Maileinstellungen</h3><h3 class="printonly">E-Maileinstellungen</h3>
	<?php $settings = $this->db->getSettings(); ?>
	<table class="striped">
		<tr>
			<th></th>
			<th></th>
		</tr>
		<tr>
			<th>SMTP Ausgangs-Server</th>
			<td><div class="editable mail" tabindex="0" data-value="SMTP_HOST" data-validator="host"><?php echo $settings['SMTP_HOST']; ?></div></td>
		</tr>
		<tr>
			<th>SMTP Nutzer</th>
			<td><div class="editable mail" tabindex="0" data-value="SMTP_USER" data-validator="username"><?php echo $settings['SMTP_USER']; ?></div></td>
		</tr>
		<tr>
			<th>SMTP Passwort</th>
			<td><div class="editable mail" tabindex="0" data-value="MAIL_PASSWORD" data-validator="password"><?php for ($i=0; $i<16; $i++) echo '&#8226;'; ?></div></td>
		</tr>
		<tr>
			<th>SMTP Sicherheit</th>
			<td><div class="editable mail" tabindex="0" data-value="SMTP_SECURE" data-validator="ssltls"><?php echo $settings['SMTP_SECURE']; ?></div></td>
		</tr>
		<tr>
			<th>SMTP Port</th>
			<td><div class="editable mail" tabindex="0" data-value="SMTP_PORT" data-validator="integer"><?php echo $settings['SMTP_PORT']; ?></div></td>
		</tr>
		<tr>
			<th>Absender E-Mailadresse</th>
			<td><div class="editable mail" tabindex="0" data-value="MAIL_FROM" data-validator="mail"><?php echo $settings['MAIL_FROM']; ?></div></td>
		</tr>
		<tr>
			<th>Absender Name</th>
			<td><div class="editable mail" tabindex="0" data-value="MAIL_FROM_ALIAS" data-validator="user"><?php echo $settings['MAIL_FROM_ALIAS']; ?></div></td>
		</tr>
	</table>
	<div class="addfooterspace"></div>
	<div class="footerline">
		<button type="button" class="submit" title="Einstellungen testen. Dabei wird eine E-Mail versendet.">Einstellungen testen</button>
	</div>
</div>
<div class="clear"></div>