<h3><?php $committee = ucwords( $param['committee'], " \t\r\n\f\v-"); echo $committee; ?> - Beschlussliste</h3>
<p class="mb-2"><strong>(Gesammt: <span class="resocounter"><?= count($param['reso']) ?></span>)</strong></p>

<?php
$this->t->appendFloatingLink(WIKI_URL."/".str_replace(':', '/', self::$protomap[$param['committee']][2]), "Wiki Beschlussliste", '&#xf266;');
?>

<div class="resol_legend noselect mb-1">
	<div class="legendelem legend-order" data-filter="<?= $param['order']=='DESC'?'0':'1' ?>" data-type="order">
		<span class="color" style="background-color:#ff5000;"><i data-class0="fa-chevron-up" data-class1="fa-chevron-down" class="fa <?= $param['order']=='DESC'?'fa-chevron-up':'fa-chevron-down' ?> align-top pl-1 mt-4p text-white fonts-half"></i></span>
		<span class="name" data-text0="Sortierung: Neuste zuerst" data-text1="Sortierung: Älteste zuerst"><?= $param['order']=='DESC'?'Sortierung: Neuste zuerst':'Sortierung: Älteste zuerst' ?></span>
	</div>
	<div class="legendelem legend-year relative" data-type=y>
		<span class="name">Nach Jahr filtern:</span>
		<select class="filter_select" id="year-filter">
			<option value="">Nichts ausgewählt</option>
			<?php 
				$now = date_create();
				$cy = intval($now->format('Y'));
				for ($i = 2009; $i <= $cy; $i++){
					echo "\n\t<option value=\"$i\"".((isset($param['year'])&& $i == $param['year'])?' selected':'').">$i</option>";
				}
			?>
		</select><i class="filter_select_arrow fa fa-chevron-down"></i>
	</div>
</div>

<div class="search-filter">
	<span class="printonly">Suche: </span>
	<details>
		<summary>Zum Filtern hier Suchwort eingeben.</summary>
		<div class="desc noprint">
			Um nach einem Beschlusstyp zu filtern, kann den Suchbegriffen ein <code>#</code> vorangestellt werdem, gefolgt vom Kürzelbuchstaben oder dem Typ.
			<br><br>
			<strong>Beispiel: Beschluss betrifft<span class="asterisk">*</span> ...</strong>
			<ul>
				<li><code>#T</code> oder <code>#Tagesordnung</code></li>
				<li><code>#P</code> oder <code>#Protokoll</code>e</li>
				<li><code>#O</code> oder <code>#Ordnungen</code></li>
				<li><code>#W</code> oder <code>#Wahl</code>en</li>
				<li><code>#F</code><span class="asterisk">**</span> oder <code>#Finanzen</code><span class="asterisk">****</span></li>
				<li><code>#H</code><span class="asterisk">***</span> oder <code data-search-append="en">#Finanz</code>beschluss des Haushaltsverantwortlichen</li>
				<li><code>#S</code> oder <code>#Sonstiges</code></li>
			</ul>
			<div class="comment"><span class="asterisk">*</span><span>Die Beschlüsse werden seit 2018 automatisch kategorisiert. Keine Gewähr bei fehlerhaft zugeordneten Kategorien.</span></div>
			<div class="comment"><span class="asterisk">**</span><span>Finanzbeschlüsse ohne die des Haushaltsverantwortlichen</span></div>
			<div class="comment"><span class="asterisk">***</span><span>Ausschließlich Finanzbeschlüsse des Haushaltsverantwortlichen</span></div>
			<div class="comment"><span class="asterisk">****</span><span>Alle Finanzbeschlüsse</span></div>
		</div>
	</details>
</div>
<input class="form-control noprint" id="resofilter" type="text" style="display: none;" placeholder="Suche..">
<br>

<div id="resotable" class="resolist-table">
	<table class="table table-striped table-sm">
		<thead>
			<tr>
				<th scope="col">#</th>
				<th style="max-width: 130px" scope="col">Typ</th>
				<th scope="col">Beschluss</th>
			</tr>
		</thead>
		<tbody>
		<?php
		$last_legislatur = 0;
		$last_week = 0;
		$last_proto_id = 0;
		$week_reso_reset = false;
		foreach ($param['reso'] as $pos => $reso){
			$week_reso_reset = false;
			$legislatur = substr($reso['r_tag'], 0, strpos($reso['r_tag'], '/'));
			$week = substr($reso['r_tag'], strpos($reso['r_tag'], '/') + 1);
			$week = substr($week, 0, strpos($week, '-'));

			if ($last_legislatur != $legislatur){ //legislatur headline
				$last_legislatur = $legislatur;
				echo '<tr class="newlegislatur"><th colspan="3" class="newlegislatur  table-dark" scope="row"><div class="position-relative"><div id="legis-'.$legislatur.'" class="reftag top-130"></div></div>'."$legislatur. $committee-Legislatur</th></tr>";
				$this->t->appendFloatingLink( '#legis-'.$legislatur, 'Legislatur '.$legislatur , '&#xf0c1;');
			}
			if ($last_week != $week){ // week headline
				$last_week = $week;
				$week_reso_reset = true;
				echo '<tr class="newweek table-success"><th colspan="3" class="newweek" scope="row">'."Woche $week. - ".(($reso['on_protocol'])?"Protokoll vom <a href=\"".WIKI_URL.'/'.self::$protomap[$param['committee']][1].':'.$reso['pname']."\" target=\"_blank\">{$reso['date']}</a>":'Protokoll vom '.$reso['pname'])."</th></tr>";
			}
			if ($last_proto_id != $reso['pid'] && !$week_reso_reset){ //second meeting in same week
				$last_proto_id = $reso['pid'];
				echo '<tr class="newweek newprotoinweek table-warning"><th colspan="3" class="newweek" scope="row">'."Woche $week. - ".(($reso['on_protocol'])?"Protokoll vom <a href=\"".WIKI_URL.'/'.self::$protomap[$param['committee']][1].':'.$reso['pname']."\" target=\"_blank\">{$reso['date']}</a>":'Protokoll vom '.$reso['pname'])."</th></tr>";
			} else {
				$last_proto_id = $reso['pid'];
				$week_reso_reset = true;
			}
			echo '<tr id="reso-'.str_replace('/', '_', $reso['r_tag']).'" class="resolution resotype-'.$reso['type_short'].' resotype-'.$reso['type_long'].'"><th style="width: 90px" scope="row">'.$reso['r_tag'].'</th>';
			echo "<td style=\"max-width: 130px\" class=\"reso-short-{$reso['type_short']}\">{$reso['type_long']}</td><td>{$reso['Titel']}";
			echo "<div class=\"d-none noprint\">{$reso['date']} Woche $last_week</div>";
			echo '<input class="resotoggle" id="reso_toggle_'.$pos.'" type="checkbox" value="1">';
			echo '<label tabindex="0" class="label resotoggle btn btn-outline-info" for="reso_toggle_'.$pos.'"></label>';
			echo '<div class="togglebox" tabindex="-1">';
			if (isset($reso['Ja'])) echo "<span class='yes'>Ja: {$reso['Ja']}</span>";
			if (isset($reso['Nein'])) echo "<span class='no'>Nein: {$reso['Nein']}</span>";
			if (isset($reso['Enthaltungen'])) echo "<span class='abstention'>Enthaltungen: {$reso['Enthaltungen']}</span>";
			echo "<span class='result'>Beschluss: {$reso['Beschluss']}</span>";
			if (isset($reso['Link'])) echo "<span class='link'>Link: <a href=\"{$reso['Link']}\" target=\"_blank\">{$reso['Link']}</a></span>";
			if (isset($reso['p_tag'])){
				if ($reso['p_tag']) echo "<span class='ptag'>Protokoll: {$reso['p_tag']}</span>";
				else echo "<span class='ptag'>Protokoll: PARSE ERROR</span>";
			}
			echo "<span class='category'>Kategorie: {$reso['type_long']}</span></div></td></tr>\n";
		}
		
		?>
		</tbody>
	</table>
</div>



<?php

foreach ($param['reso'] as $reso){
	//echo '<pre>'; var_export($reso); echo '</pre>';
}