<h3><?= ucwords( $param['committee'], " \t\r\n\f\v-"); ?> - Protokolle</h3>
<p><strong>(Gefunden: <?= count($param['int_ext']) ?> - Veröffentlicht: <?= $param['counter']['published'] .(($param['counter']['draft']>0)?' - Entwurf: '.$param['counter']['draft']:''); ?>)</strong></p>

<div class="protolist">
<?php

$esc_PROTO_IN = str_replace(':', '/', self::$protomap[$param['committee']][0]);
$esc_PROTO_OUT = str_replace(':', '/', self::$protomap[$param['committee']][1]);
$lastYearLine = '';
$this->t->appendFloatingLink(WIKI_URL."/$esc_PROTO_IN", "Wiki Intern", '&#xf266;');
$this->t->appendFloatingLink(WIKI_URL."/$esc_PROTO_OUT", "Wiki Öffentlich", '&#xf266;');
foreach ($param['int_ext'] as $pname => $v){
	if (substr($pname,0, 2)!='20') continue;
	$year = substr($pname, 0, 4);
	//year heading
	if ($lastYearLine != $year){
		$lastYearLine = $year;
		echo '<div class="yearline"><div class="yearline-link" id="year-'.$year.'"></div>'.$year.'</div>';
		$this->t->appendFloatingLink('#year-'.$year, $year, '&#xf0c1;');
	}
	$state = (isset($v['extern']))? (isset($v['draft'])?'draft':'public') : (isset($v['intern'])? 'private' : 'none');
	echo '<div id="proto-'.$pname.'" class="proto '.$state.(isset($v['agreed'])?' agreed':'').'">'.
			"<span>$pname</span>". //protocol name
			'<div class="pbc">'. //proto button container
			(isset($v['intern'])?
				'<button class="btn btn-outline-dark compare" type="button">'.(isset($v['extern'])?'Untersuchen':'Veröffentlichen').'</button>':
				'<div class="btn placeholder"></div>').
			(isset($v['reso'])?
				'<a href="/reso/list?pid='.$v['id'].'" title="Beschlüsse" class="btn resolink btn-outline-danger ml-1"><i class="fa fa-fw fa-list-ol"></i></a>':'').
			(isset($v['intern'])?
				'<span><a class="intern" href="'.WIKI_URL.'/'.$esc_PROTO_IN.'/'.$pname.'" target="_blank">Intern</a></span>':'').
			(isset($v['extern'])?(($state == 'draft')?
				'<span><a class="draft" href="'.WIKI_URL.'/'.$esc_PROTO_OUT.'/'.$pname.'" target="_blank">Entwurf</a></span>':
				'<span><a class="public" href="'.WIKI_URL.'/'.$esc_PROTO_OUT.'/'.$pname.'" target="_blank">Öffentlich</a></span>'):'').
			'</div>'.
		'</div>';
} ?>
</div>