<h3><?= ucwords( $param['committee'], " \t\r\n\f\v-"); ?> - Protokolle</h3>
<p><strong>(Gefunden: <?= count($param['int_ext']) ?> - Veröffentlicht: <?= count($param['ext']) .((count($param['drafts'])>0)?' - Entwurf: '.count($param['drafts']):''); ?>)</strong></p>

<div class="protolist">
<?php

$esc_PROTO_IN = str_replace(':', '/', self::$protomap[$param['committee']][0]);
$esc_PROTO_OUT = str_replace(':', '/', self::$protomap[$param['committee']][1]);
$lastYearLine = '';
$this->t->appendFloatingLink(WIKI_URL."/$esc_PROTO_IN", "Wiki Intern", '&#xf266;');
$this->t->appendFloatingLink(WIKI_URL."/$esc_PROTO_OUT", "Wiki Öffentlich", '&#xf266;');
foreach ($param['int_ext'] as $p => $v){
	if (substr($p,0, 2)!='20') continue;
	$year = substr($p, 0, 4);
		
	if ($lastYearLine != $year){
		$lastYearLine = $year;
		echo '<div class="yearline"><div class="yearline-link" id="year-'.$year.'"></div>'.$year.'</div>';
		$this->t->appendFloatingLink('#year-'.$year, $year, '&#xf0c1;');
	}
	if (!isset($param['no_int'][$p])){
		$state = (!isset($param['ext'][$p]))?
		'private' :
		(isset($param['drafts'][$p])?
			'draft' :
			'public');
		echo '<div id="proto-'.$p.'" class="proto '.$state.'">'.
			"<span>$p</span>".
			"<div  class='pbc'>". //proto button container
			(($state != 'public')?'<button class="btn btn-outline-dark compare" type="button">Veröffentlichen</button>':'<button class="btn btn-outline-dark compare" type="button">Untersuchen</button>').
			(isset($param['name_id'][$p])?'<a href="/resolist?pid='.$param['name_id'][$p].'" title="Beschlüsse" class="btn resolink btn-outline-danger ml-1"><i class="fa fa-fw fa-list-ol"></i></a>':'').
			'<span><a href="'.WIKI_URL.'/'.$esc_PROTO_IN.'/'.$p.'" target="_blank">Intern</a></span>'.
			(($state == 'draft')?'<span><a class="draft" href="'.WIKI_URL.'/'.$esc_PROTO_OUT.'/'.$p.'" target="_blank">Entwurf</a></span>':'').
			(($state == 'public')?'<span><a class="public" href="'.WIKI_URL.'/'.$esc_PROTO_OUT.'/'.$p.'" target="_blank">Öffentlich</a></span>':'').
			'</div></div>';
	} else {
		echo '<div id="proto-'.$p.'" class="proto public">'.
			"<span>$p</span><div class='pbc'>".
			'<div class="btn placeholder" type="button"></div>'.
			(isset($param['name_id'][$p])?'<a href="/resolist?pid='.$param['name_id'][$p].'" title="Beschlüsse" class="btn resolink btn-outline-danger ml-1"><i class="fa fa-fw fa-list-ol"></i></a>':'').
			'<span><a class="public" href="'.WIKI_URL.'/'.$esc_PROTO_OUT.'/'.$p.'" target="_blank">Öffentlich</a></span>'.
			'</div></div>';
	}
}
echo '</div>';